---
- name: Subscribe to rhel-7-server-cert-rpms
  become: true
  rhsm_repository:
    name: rhel-7-server-cert-rpms
    state: enabled
  when: openstack_certification_enable_rhsm_repo

- name: Copy an openstack certification repository
  become: true
  copy:
    src: "{{ openstack_certification_repo_file }}"
    dest: /etc/yum.repos.d/{{ openstack_certification_repo_file | basename }}
  when: openstack_certification_repo_file is defined

- name: Install Red Hat certification packages
  become: true
  package:
    name: "{{ openstack_certification_install_rpms }}"
    state: present
